title: Lab Escape
email: lab.escape.fit@gmail.com
baseurl: "/"
url: "https://labescape.github.io"
github_username: LabEscape

# Build settings
theme: null
markdown: kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
